### ISSUE TITLE
Easilly extend test probes

### ISSUE THREAD

**Issue by gfriloux** [Lex-Persona/SupExt#1]
Hello,

I am currently trying your app.
It seems interesting to me (after disabling the ES part that i dont need), but i would like to be able to more easilly extend the probe types, knowing i dont know python at all.

Currently, if im not wrong, there is 2 types of probes : 
1. HTTP : Querying an URL, and check if returned value is 200. If not, raise en error.
2. TCP : Checking if port is open or not.

This is too limited for what could be my "use case".

Here is an extract of probes i would need : 
1. Check that we can login to an ssh server using a specific key.
2. Check that an FQDN resolves correctly.
3. Validate an HTTP cert expiration date.

I am able to write thoses using standard tools and bash.
I am not able to do it in python.

Would you consider to create a third test probe that would allow to execute commands/scripts ?
I understand that while the question looks easy, having this feature to properlly integrate with templating etc might be harder, but this might then unlock contributions for more probe types from more people, at least me.

What do you think about it ?

**Comment by prototux** [comment]
Hello,

There's already bash wrappers and SSL certs probes in our internal version, i'm planning on releasing them as soon as i've removed any confidential informations (mostly hardcoded parts that should go in the config fle) in them :smile: 

As I'm currently in vacations, i'm not able to clean/release these probes this week, but i will do it next week.

It is also planned to be able to activate/desactivate modules such as mail alert and elasticsearch as well.

**Comment by gfriloux** [comment]
Ok, thx :)

**Comment by prototux** [comment]
The 3 requested modules + a generic shell script wrapper are available now.
