### ISSUE TITLE
Having groups of mailgroups for checks

### ISSUE THREAD

**Issue by gfriloux** [Lex-Persona/SupExt#8]
A check can be attached to a mail alert.
This is done using : 
> mail: { group: "group1" }

Inside the check declaration.

It can be a lot easier for users to define a list of groups to contact.
One format could be : 
> mail: { groups: ["group1", "group2"] }

This proposal would break actual configuration.

**Comment by prototux** [comment]
It is possible to detect if group is a string or a list, and act accordingly, so it is possible to implement this feature without breaking changes, that's what i'll probably do.
